/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Career Quest API
 * API кейса Career Quest. Синтетические данные, дата среза из meta.as_of_date. HttpOnly cookie-сессия; сотрудник видит только себя, HR — профили, аналитику и импорт. Расчетный режим явно отделен от AI.
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from '../lib/client/custom-instance';
export type Health200 = {
  status: string;
  ai_configured: boolean;
  agent_available: boolean;
};

export type Health400 = {
  message: string;
};

export type Health401 = {
  message: string;
};

export type Health403 = {
  message: string;
};

export type Health404 = {
  message: string;
};

export type Health409 = {
  message: string;
};

export type Health413 = {
  message: string;
};

export type Health429 = {
  message: string;
};

export type Health500 = {
  message: string;
};

export type LoginBodyOne = {
  /**
     * @minLength 1
     * @maxLength 128
     */
  username: string;
  /**
     * @minLength 1
     * @maxLength 1024
     */
  password: string;
};

export type LoginBodyTwo = {
  /**
     * @minLength 1
     * @maxLength 128
     */
  username: string;
  /**
     * @minLength 1
     * @maxLength 1024
     */
  password: string;
};

export type LoginBodyThree = {
  /**
     * @minLength 1
     * @maxLength 128
     */
  username: string;
  /**
     * @minLength 1
     * @maxLength 1024
     */
  password: string;
};

export type Login200Role = typeof Login200Role[keyof typeof Login200Role];


export const Login200Role = {
  employee: 'employee',
  hr: 'hr',
} as const;

export type Login200 = {
  username: string;
  role: Login200Role;
  /** @nullable */
  employee_id: string | null;
  full_name: string;
};

export type Login400 = {
  message: string;
};

export type Login401 = {
  message: string;
};

export type Login403 = {
  message: string;
};

export type Login404 = {
  message: string;
};

export type Login409 = {
  message: string;
};

export type Login413 = {
  message: string;
};

export type Login429 = {
  message: string;
};

export type Login500 = {
  message: string;
};

export type GetSession200Role = typeof GetSession200Role[keyof typeof GetSession200Role];


export const GetSession200Role = {
  employee: 'employee',
  hr: 'hr',
} as const;

export type GetSession200 = {
  username: string;
  role: GetSession200Role;
  /** @nullable */
  employee_id: string | null;
  full_name: string;
};

export type GetSession400 = {
  message: string;
};

export type GetSession401 = {
  message: string;
};

export type GetSession403 = {
  message: string;
};

export type GetSession404 = {
  message: string;
};

export type GetSession409 = {
  message: string;
};

export type GetSession413 = {
  message: string;
};

export type GetSession429 = {
  message: string;
};

export type GetSession500 = {
  message: string;
};

export type Logout200 = {
  ok: true;
};

export type Logout400 = {
  message: string;
};

export type Logout401 = {
  message: string;
};

export type Logout403 = {
  message: string;
};

export type Logout404 = {
  message: string;
};

export type Logout409 = {
  message: string;
};

export type Logout413 = {
  message: string;
};

export type Logout429 = {
  message: string;
};

export type Logout500 = {
  message: string;
};

export type GetEmployees200EmployeesItemGrade = typeof GetEmployees200EmployeesItemGrade[keyof typeof GetEmployees200EmployeesItemGrade];


export const GetEmployees200EmployeesItemGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

export type GetEmployees200EmployeesItem = {
  employee_id: string;
  full_name: string;
  role: string;
  grade: GetEmployees200EmployeesItemGrade;
  department: string;
};

export type GetEmployees200 = {
  employees: GetEmployees200EmployeesItem[];
};

export type GetEmployees400 = {
  message: string;
};

export type GetEmployees401 = {
  message: string;
};

export type GetEmployees403 = {
  message: string;
};

export type GetEmployees404 = {
  message: string;
};

export type GetEmployees409 = {
  message: string;
};

export type GetEmployees413 = {
  message: string;
};

export type GetEmployees429 = {
  message: string;
};

export type GetEmployees500 = {
  message: string;
};

export type GetProfile200EmployeeGrade = typeof GetProfile200EmployeeGrade[keyof typeof GetProfile200EmployeeGrade];


export const GetProfile200EmployeeGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

export type GetProfile200EmployeeWorkFormat = typeof GetProfile200EmployeeWorkFormat[keyof typeof GetProfile200EmployeeWorkFormat];


export const GetProfile200EmployeeWorkFormat = {
  office: 'office',
  hybrid: 'hybrid',
  remote: 'remote',
} as const;

export type GetProfile200EmployeePreferredLanguage = typeof GetProfile200EmployeePreferredLanguage[keyof typeof GetProfile200EmployeePreferredLanguage];


export const GetProfile200EmployeePreferredLanguage = {
  ru: 'ru',
  kk: 'kk',
  en: 'en',
} as const;

export type GetProfile200EmployeeCareerGoalTargetGrade = typeof GetProfile200EmployeeCareerGoalTargetGrade[keyof typeof GetProfile200EmployeeCareerGoalTargetGrade];


export const GetProfile200EmployeeCareerGoalTargetGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

/**
 * @nullable
 */
export type GetProfile200EmployeeCareerGoal = {
  /** @minLength 1 */
  target_role: string;
  target_grade: GetProfile200EmployeeCareerGoalTargetGrade;
} | null;

export type GetProfile200EmployeeSkills = { [key: string]: unknown };

export type GetProfile200Employee = {
  employee_id: string;
  full_name: string;
  department: string;
  role: string;
  grade: GetProfile200EmployeeGrade;
  /** @nullable */
  manager_id: string | null;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  hire_date: string;
  tenure_months: number;
  work_format: GetProfile200EmployeeWorkFormat;
  preferred_language: GetProfile200EmployeePreferredLanguage;
  /** @nullable */
  career_goal: GetProfile200EmployeeCareerGoal;
  skills: GetProfile200EmployeeSkills;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  last_review_date: string;
};

export type GetProfile200EffectiveSkills = { [key: string]: unknown };

export type GetProfile200TargetTargetGrade = typeof GetProfile200TargetTargetGrade[keyof typeof GetProfile200TargetTargetGrade];


export const GetProfile200TargetTargetGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

/**
 * @nullable
 */
export type GetProfile200Target = {
  /** @minLength 1 */
  target_role: string;
  target_grade: GetProfile200TargetTargetGrade;
} | null;

export type GetProfile200TargetSource = typeof GetProfile200TargetSource[keyof typeof GetProfile200TargetSource];


export const GetProfile200TargetSource = {
  explicit: 'explicit',
  next_grade: 'next_grade',
  none: 'none',
} as const;

export type GetProfile200GapsItem = {
  skill_id: string;
  name: string;
  current: number;
  required: number;
  gap: number;
  critical: boolean;
  covered: boolean;
};

export type GetProfile200HistoryItemStatus = typeof GetProfile200HistoryItemStatus[keyof typeof GetProfile200HistoryItemStatus];


export const GetProfile200HistoryItemStatus = {
  completed: 'completed',
  in_progress: 'in_progress',
  dropped: 'dropped',
  no_show: 'no_show',
  declined: 'declined',
  overdue: 'overdue',
} as const;

export type GetProfile200HistoryItemAssignedBy = typeof GetProfile200HistoryItemAssignedBy[keyof typeof GetProfile200HistoryItemAssignedBy];


export const GetProfile200HistoryItemAssignedBy = {
  self: 'self',
  manager: 'manager',
  hr: 'hr',
} as const;

export type GetProfile200HistoryItem = {
  record_id: string;
  employee_id: string;
  event_id: string;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  date: string;
  /**
     * @nullable
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  due_date: string | null;
  status: GetProfile200HistoryItemStatus;
  /**
     * @minimum 0
     * @maximum 100
     */
  completion_pct: number;
  /** @nullable */
  score: number | null;
  /** @nullable */
  feedback_rating: number | null;
  assigned_by: GetProfile200HistoryItemAssignedBy;
  /** @nullable */
  completed_at?: string | null;
  title: string;
  mandatory: boolean;
};

export type GetProfile200 = {
  employee: GetProfile200Employee;
  effective_skills: GetProfile200EffectiveSkills;
  /** @nullable */
  target: GetProfile200Target;
  target_source: GetProfile200TargetSource;
  /** @nullable */
  readiness: number | null;
  gaps: GetProfile200GapsItem[];
  history: GetProfile200HistoryItem[];
  warnings: string[];
};

export type GetProfile400 = {
  message: string;
};

export type GetProfile401 = {
  message: string;
};

export type GetProfile403 = {
  message: string;
};

export type GetProfile404 = {
  message: string;
};

export type GetProfile409 = {
  message: string;
};

export type GetProfile413 = {
  message: string;
};

export type GetProfile429 = {
  message: string;
};

export type GetProfile500 = {
  message: string;
};

export type UpdateGoalBodyOneGoalTargetGrade = typeof UpdateGoalBodyOneGoalTargetGrade[keyof typeof UpdateGoalBodyOneGoalTargetGrade];


export const UpdateGoalBodyOneGoalTargetGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

/**
 * @nullable
 */
export type UpdateGoalBodyOneGoal = {
  /** @minLength 1 */
  target_role: string;
  target_grade: UpdateGoalBodyOneGoalTargetGrade;
} | null;

export type UpdateGoalBodyOne = {
  /** @nullable */
  goal: UpdateGoalBodyOneGoal;
};

export type UpdateGoalBodyTwoGoalTargetGrade = typeof UpdateGoalBodyTwoGoalTargetGrade[keyof typeof UpdateGoalBodyTwoGoalTargetGrade];


export const UpdateGoalBodyTwoGoalTargetGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

/**
 * @nullable
 */
export type UpdateGoalBodyTwoGoal = {
  /** @minLength 1 */
  target_role: string;
  target_grade: UpdateGoalBodyTwoGoalTargetGrade;
} | null;

export type UpdateGoalBodyTwo = {
  /** @nullable */
  goal: UpdateGoalBodyTwoGoal;
};

export type UpdateGoalBodyThreeGoalTargetGrade = typeof UpdateGoalBodyThreeGoalTargetGrade[keyof typeof UpdateGoalBodyThreeGoalTargetGrade];


export const UpdateGoalBodyThreeGoalTargetGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

/**
 * @nullable
 */
export type UpdateGoalBodyThreeGoal = {
  /** @minLength 1 */
  target_role: string;
  target_grade: UpdateGoalBodyThreeGoalTargetGrade;
} | null;

export type UpdateGoalBodyThree = {
  /** @nullable */
  goal: UpdateGoalBodyThreeGoal;
};

export type UpdateGoal200EmployeeGrade = typeof UpdateGoal200EmployeeGrade[keyof typeof UpdateGoal200EmployeeGrade];


export const UpdateGoal200EmployeeGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

export type UpdateGoal200EmployeeWorkFormat = typeof UpdateGoal200EmployeeWorkFormat[keyof typeof UpdateGoal200EmployeeWorkFormat];


export const UpdateGoal200EmployeeWorkFormat = {
  office: 'office',
  hybrid: 'hybrid',
  remote: 'remote',
} as const;

export type UpdateGoal200EmployeePreferredLanguage = typeof UpdateGoal200EmployeePreferredLanguage[keyof typeof UpdateGoal200EmployeePreferredLanguage];


export const UpdateGoal200EmployeePreferredLanguage = {
  ru: 'ru',
  kk: 'kk',
  en: 'en',
} as const;

export type UpdateGoal200EmployeeCareerGoalTargetGrade = typeof UpdateGoal200EmployeeCareerGoalTargetGrade[keyof typeof UpdateGoal200EmployeeCareerGoalTargetGrade];


export const UpdateGoal200EmployeeCareerGoalTargetGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

/**
 * @nullable
 */
export type UpdateGoal200EmployeeCareerGoal = {
  /** @minLength 1 */
  target_role: string;
  target_grade: UpdateGoal200EmployeeCareerGoalTargetGrade;
} | null;

export type UpdateGoal200EmployeeSkills = { [key: string]: unknown };

export type UpdateGoal200Employee = {
  employee_id: string;
  full_name: string;
  department: string;
  role: string;
  grade: UpdateGoal200EmployeeGrade;
  /** @nullable */
  manager_id: string | null;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  hire_date: string;
  tenure_months: number;
  work_format: UpdateGoal200EmployeeWorkFormat;
  preferred_language: UpdateGoal200EmployeePreferredLanguage;
  /** @nullable */
  career_goal: UpdateGoal200EmployeeCareerGoal;
  skills: UpdateGoal200EmployeeSkills;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  last_review_date: string;
};

export type UpdateGoal200EffectiveSkills = { [key: string]: unknown };

export type UpdateGoal200TargetTargetGrade = typeof UpdateGoal200TargetTargetGrade[keyof typeof UpdateGoal200TargetTargetGrade];


export const UpdateGoal200TargetTargetGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

/**
 * @nullable
 */
export type UpdateGoal200Target = {
  /** @minLength 1 */
  target_role: string;
  target_grade: UpdateGoal200TargetTargetGrade;
} | null;

export type UpdateGoal200TargetSource = typeof UpdateGoal200TargetSource[keyof typeof UpdateGoal200TargetSource];


export const UpdateGoal200TargetSource = {
  explicit: 'explicit',
  next_grade: 'next_grade',
  none: 'none',
} as const;

export type UpdateGoal200GapsItem = {
  skill_id: string;
  name: string;
  current: number;
  required: number;
  gap: number;
  critical: boolean;
  covered: boolean;
};

export type UpdateGoal200HistoryItemStatus = typeof UpdateGoal200HistoryItemStatus[keyof typeof UpdateGoal200HistoryItemStatus];


export const UpdateGoal200HistoryItemStatus = {
  completed: 'completed',
  in_progress: 'in_progress',
  dropped: 'dropped',
  no_show: 'no_show',
  declined: 'declined',
  overdue: 'overdue',
} as const;

export type UpdateGoal200HistoryItemAssignedBy = typeof UpdateGoal200HistoryItemAssignedBy[keyof typeof UpdateGoal200HistoryItemAssignedBy];


export const UpdateGoal200HistoryItemAssignedBy = {
  self: 'self',
  manager: 'manager',
  hr: 'hr',
} as const;

export type UpdateGoal200HistoryItem = {
  record_id: string;
  employee_id: string;
  event_id: string;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  date: string;
  /**
     * @nullable
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  due_date: string | null;
  status: UpdateGoal200HistoryItemStatus;
  /**
     * @minimum 0
     * @maximum 100
     */
  completion_pct: number;
  /** @nullable */
  score: number | null;
  /** @nullable */
  feedback_rating: number | null;
  assigned_by: UpdateGoal200HistoryItemAssignedBy;
  /** @nullable */
  completed_at?: string | null;
  title: string;
  mandatory: boolean;
};

export type UpdateGoal200 = {
  employee: UpdateGoal200Employee;
  effective_skills: UpdateGoal200EffectiveSkills;
  /** @nullable */
  target: UpdateGoal200Target;
  target_source: UpdateGoal200TargetSource;
  /** @nullable */
  readiness: number | null;
  gaps: UpdateGoal200GapsItem[];
  history: UpdateGoal200HistoryItem[];
  warnings: string[];
};

export type UpdateGoal400 = {
  message: string;
};

export type UpdateGoal401 = {
  message: string;
};

export type UpdateGoal403 = {
  message: string;
};

export type UpdateGoal404 = {
  message: string;
};

export type UpdateGoal409 = {
  message: string;
};

export type UpdateGoal413 = {
  message: string;
};

export type UpdateGoal429 = {
  message: string;
};

export type UpdateGoal500 = {
  message: string;
};

export type CompleteActivityBodyOne = { [key: string]: unknown };

export type CompleteActivityBodyTwo = { [key: string]: unknown };

export type CompleteActivityBodyThree = { [key: string]: unknown };

export type CompleteActivity200ProfileEmployeeGrade = typeof CompleteActivity200ProfileEmployeeGrade[keyof typeof CompleteActivity200ProfileEmployeeGrade];


export const CompleteActivity200ProfileEmployeeGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

export type CompleteActivity200ProfileEmployeeWorkFormat = typeof CompleteActivity200ProfileEmployeeWorkFormat[keyof typeof CompleteActivity200ProfileEmployeeWorkFormat];


export const CompleteActivity200ProfileEmployeeWorkFormat = {
  office: 'office',
  hybrid: 'hybrid',
  remote: 'remote',
} as const;

export type CompleteActivity200ProfileEmployeePreferredLanguage = typeof CompleteActivity200ProfileEmployeePreferredLanguage[keyof typeof CompleteActivity200ProfileEmployeePreferredLanguage];


export const CompleteActivity200ProfileEmployeePreferredLanguage = {
  ru: 'ru',
  kk: 'kk',
  en: 'en',
} as const;

export type CompleteActivity200ProfileEmployeeCareerGoalTargetGrade = typeof CompleteActivity200ProfileEmployeeCareerGoalTargetGrade[keyof typeof CompleteActivity200ProfileEmployeeCareerGoalTargetGrade];


export const CompleteActivity200ProfileEmployeeCareerGoalTargetGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

/**
 * @nullable
 */
export type CompleteActivity200ProfileEmployeeCareerGoal = {
  /** @minLength 1 */
  target_role: string;
  target_grade: CompleteActivity200ProfileEmployeeCareerGoalTargetGrade;
} | null;

export type CompleteActivity200ProfileEmployeeSkills = { [key: string]: unknown };

export type CompleteActivity200ProfileEmployee = {
  employee_id: string;
  full_name: string;
  department: string;
  role: string;
  grade: CompleteActivity200ProfileEmployeeGrade;
  /** @nullable */
  manager_id: string | null;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  hire_date: string;
  tenure_months: number;
  work_format: CompleteActivity200ProfileEmployeeWorkFormat;
  preferred_language: CompleteActivity200ProfileEmployeePreferredLanguage;
  /** @nullable */
  career_goal: CompleteActivity200ProfileEmployeeCareerGoal;
  skills: CompleteActivity200ProfileEmployeeSkills;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  last_review_date: string;
};

export type CompleteActivity200ProfileEffectiveSkills = { [key: string]: unknown };

export type CompleteActivity200ProfileTargetTargetGrade = typeof CompleteActivity200ProfileTargetTargetGrade[keyof typeof CompleteActivity200ProfileTargetTargetGrade];


export const CompleteActivity200ProfileTargetTargetGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

/**
 * @nullable
 */
export type CompleteActivity200ProfileTarget = {
  /** @minLength 1 */
  target_role: string;
  target_grade: CompleteActivity200ProfileTargetTargetGrade;
} | null;

export type CompleteActivity200ProfileTargetSource = typeof CompleteActivity200ProfileTargetSource[keyof typeof CompleteActivity200ProfileTargetSource];


export const CompleteActivity200ProfileTargetSource = {
  explicit: 'explicit',
  next_grade: 'next_grade',
  none: 'none',
} as const;

export type CompleteActivity200ProfileGapsItem = {
  skill_id: string;
  name: string;
  current: number;
  required: number;
  gap: number;
  critical: boolean;
  covered: boolean;
};

export type CompleteActivity200ProfileHistoryItemStatus = typeof CompleteActivity200ProfileHistoryItemStatus[keyof typeof CompleteActivity200ProfileHistoryItemStatus];


export const CompleteActivity200ProfileHistoryItemStatus = {
  completed: 'completed',
  in_progress: 'in_progress',
  dropped: 'dropped',
  no_show: 'no_show',
  declined: 'declined',
  overdue: 'overdue',
} as const;

export type CompleteActivity200ProfileHistoryItemAssignedBy = typeof CompleteActivity200ProfileHistoryItemAssignedBy[keyof typeof CompleteActivity200ProfileHistoryItemAssignedBy];


export const CompleteActivity200ProfileHistoryItemAssignedBy = {
  self: 'self',
  manager: 'manager',
  hr: 'hr',
} as const;

export type CompleteActivity200ProfileHistoryItem = {
  record_id: string;
  employee_id: string;
  event_id: string;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  date: string;
  /**
     * @nullable
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  due_date: string | null;
  status: CompleteActivity200ProfileHistoryItemStatus;
  /**
     * @minimum 0
     * @maximum 100
     */
  completion_pct: number;
  /** @nullable */
  score: number | null;
  /** @nullable */
  feedback_rating: number | null;
  assigned_by: CompleteActivity200ProfileHistoryItemAssignedBy;
  /** @nullable */
  completed_at?: string | null;
  title: string;
  mandatory: boolean;
};

export type CompleteActivity200Profile = {
  employee: CompleteActivity200ProfileEmployee;
  effective_skills: CompleteActivity200ProfileEffectiveSkills;
  /** @nullable */
  target: CompleteActivity200ProfileTarget;
  target_source: CompleteActivity200ProfileTargetSource;
  /** @nullable */
  readiness: number | null;
  gaps: CompleteActivity200ProfileGapsItem[];
  history: CompleteActivity200ProfileHistoryItem[];
  warnings: string[];
};

export type CompleteActivity200 = {
  profile: CompleteActivity200Profile;
  already_completed: boolean;
};

export type CompleteActivity400 = {
  message: string;
};

export type CompleteActivity401 = {
  message: string;
};

export type CompleteActivity403 = {
  message: string;
};

export type CompleteActivity404 = {
  message: string;
};

export type CompleteActivity409 = {
  message: string;
};

export type CompleteActivity413 = {
  message: string;
};

export type CompleteActivity429 = {
  message: string;
};

export type CompleteActivity500 = {
  message: string;
};

export type GetCatalog200RolesItemGrade = typeof GetCatalog200RolesItemGrade[keyof typeof GetCatalog200RolesItemGrade];


export const GetCatalog200RolesItemGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

export type GetCatalog200RolesItemRequiredSkills = { [key: string]: unknown };

export type GetCatalog200RolesItem = {
  role: string;
  grade: GetCatalog200RolesItemGrade;
  required_skills: GetCatalog200RolesItemRequiredSkills;
  critical_skills: string[];
};

export type GetCatalog200SkillsItem = {
  skill_id: string;
  name: string;
  type: string;
  category: string;
  description: string;
};

export type GetCatalog200 = {
  roles: GetCatalog200RolesItem[];
  skills: GetCatalog200SkillsItem[];
  as_of_date: string;
};

export type GetCatalog400 = {
  message: string;
};

export type GetCatalog401 = {
  message: string;
};

export type GetCatalog403 = {
  message: string;
};

export type GetCatalog404 = {
  message: string;
};

export type GetCatalog409 = {
  message: string;
};

export type GetCatalog413 = {
  message: string;
};

export type GetCatalog429 = {
  message: string;
};

export type GetCatalog500 = {
  message: string;
};

export type GetRecommendationsBodyOne = { [key: string]: unknown };

export type GetRecommendationsBodyTwo = { [key: string]: unknown };

export type GetRecommendationsBodyThree = { [key: string]: unknown };

export type GetRecommendations200Mode = typeof GetRecommendations200Mode[keyof typeof GetRecommendations200Mode];


export const GetRecommendations200Mode = {
  ai: 'ai',
  rules: 'rules',
} as const;

export type GetRecommendations200RecommendationsItemEventFormat = typeof GetRecommendations200RecommendationsItemEventFormat[keyof typeof GetRecommendations200RecommendationsItemEventFormat];


export const GetRecommendations200RecommendationsItemEventFormat = {
  online: 'online',
  offline: 'offline',
  self_paced: 'self_paced',
} as const;

export type GetRecommendations200RecommendationsItemEventTargetGradesItem = typeof GetRecommendations200RecommendationsItemEventTargetGradesItem[keyof typeof GetRecommendations200RecommendationsItemEventTargetGradesItem];


export const GetRecommendations200RecommendationsItemEventTargetGradesItem = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

export type GetRecommendations200RecommendationsItemEventDevelopsSkillsItem = {
  skill_id: string;
  gain: number;
  /**
     * @minimum 0
     * @maximum 5
     */
  max_level: number;
};

export type GetRecommendations200RecommendationsItemEventPrerequisites = { [key: string]: unknown };

export type GetRecommendations200RecommendationsItemEvent = {
  event_id: string;
  title: string;
  description: string;
  type: string;
  format: GetRecommendations200RecommendationsItemEventFormat;
  duration_hours: number;
  mandatory: boolean;
  target_roles: string[];
  target_grades: GetRecommendations200RecommendationsItemEventTargetGradesItem[];
  develops_skills: GetRecommendations200RecommendationsItemEventDevelopsSkillsItem[];
  prerequisites: GetRecommendations200RecommendationsItemEventPrerequisites;
  /** @items.pattern ^\d{4}-\d{2}-\d{2}$ */
  upcoming_sessions: string[];
};

export type GetRecommendations200RecommendationsItemFactorsItemCategory = typeof GetRecommendations200RecommendationsItemFactorsItemCategory[keyof typeof GetRecommendations200RecommendationsItemFactorsItemCategory];


export const GetRecommendations200RecommendationsItemFactorsItemCategory = {
  grade: 'grade',
  gap: 'gap',
  history: 'history',
  target: 'target',
} as const;

export type GetRecommendations200RecommendationsItemFactorsItem = {
  id: string;
  category: GetRecommendations200RecommendationsItemFactorsItemCategory;
  text: string;
};

export type GetRecommendations200RecommendationsItemGainsItem = {
  skill_id: string;
  name: string;
  before: number;
  after: number;
  target: number;
};

export type GetRecommendations200RecommendationsItem = {
  event: GetRecommendations200RecommendationsItemEvent;
  score: number;
  factors: GetRecommendations200RecommendationsItemFactorsItem[];
  /**
     * @nullable
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  next_session: string | null;
  gains: GetRecommendations200RecommendationsItemGainsItem[];
  in_progress: boolean;
  explanation: string;
};

export type GetRecommendations200 = {
  mode: GetRecommendations200Mode;
  /** @nullable */
  model: string | null;
  message: string;
  /** @maxItems 3 */
  recommendations: GetRecommendations200RecommendationsItem[];
  generated_at: string;
  duration_ms: number;
};

export type GetRecommendations400 = {
  message: string;
};

export type GetRecommendations401 = {
  message: string;
};

export type GetRecommendations403 = {
  message: string;
};

export type GetRecommendations404 = {
  message: string;
};

export type GetRecommendations409 = {
  message: string;
};

export type GetRecommendations413 = {
  message: string;
};

export type GetRecommendations429 = {
  message: string;
};

export type GetRecommendations500 = {
  message: string;
};

export type GetCareerPlan200CurrentPositionGrade = typeof GetCareerPlan200CurrentPositionGrade[keyof typeof GetCareerPlan200CurrentPositionGrade];


export const GetCareerPlan200CurrentPositionGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

export type GetCareerPlan200CurrentPosition = {
  role: string;
  grade: GetCareerPlan200CurrentPositionGrade;
};

export type GetCareerPlan200CareerGoalTargetGrade = typeof GetCareerPlan200CareerGoalTargetGrade[keyof typeof GetCareerPlan200CareerGoalTargetGrade];


export const GetCareerPlan200CareerGoalTargetGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

/**
 * @nullable
 */
export type GetCareerPlan200CareerGoal = {
  /** @minLength 1 */
  target_role: string;
  target_grade: GetCareerPlan200CareerGoalTargetGrade;
} | null;

export type GetCareerPlan200GoalSource = typeof GetCareerPlan200GoalSource[keyof typeof GetCareerPlan200GoalSource];


export const GetCareerPlan200GoalSource = {
  explicit: 'explicit',
  next_grade: 'next_grade',
  none: 'none',
} as const;

export type GetCareerPlan200EffectiveSkills = { [key: string]: unknown };

export type GetCareerPlan200ProjectedSkills = { [key: string]: unknown };

export type GetCareerPlan200TrajectoryItem = {
  event_id: string;
  /**
     * @minimum 0
     * @maximum 100
     * @nullable
     */
  readiness_before: number | null;
  /**
     * @minimum 0
     * @maximum 100
     * @nullable
     */
  readiness_after: number | null;
};

export type GetCareerPlan200GapsItem = {
  skill_id: string;
  name: string;
  /**
     * @minimum 0
     * @maximum 5
     */
  current: number;
  /**
     * @minimum 0
     * @maximum 5
     */
  required: number;
  /**
     * @minimum 1
     * @maximum 5
     */
  gap: number;
  critical: boolean;
  covered: boolean;
};

export type GetCareerPlan200RecommendationsItemEventFormat = typeof GetCareerPlan200RecommendationsItemEventFormat[keyof typeof GetCareerPlan200RecommendationsItemEventFormat];


export const GetCareerPlan200RecommendationsItemEventFormat = {
  online: 'online',
  offline: 'offline',
  self_paced: 'self_paced',
} as const;

export type GetCareerPlan200RecommendationsItemEventTargetGradesItem = typeof GetCareerPlan200RecommendationsItemEventTargetGradesItem[keyof typeof GetCareerPlan200RecommendationsItemEventTargetGradesItem];


export const GetCareerPlan200RecommendationsItemEventTargetGradesItem = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

export type GetCareerPlan200RecommendationsItemEventDevelopsSkillsItem = {
  skill_id: string;
  gain: number;
  /**
     * @minimum 0
     * @maximum 5
     */
  max_level: number;
};

export type GetCareerPlan200RecommendationsItemEventPrerequisites = { [key: string]: unknown };

export type GetCareerPlan200RecommendationsItemEvent = {
  event_id: string;
  title: string;
  description: string;
  type: string;
  format: GetCareerPlan200RecommendationsItemEventFormat;
  duration_hours: number;
  mandatory: boolean;
  target_roles: string[];
  target_grades: GetCareerPlan200RecommendationsItemEventTargetGradesItem[];
  develops_skills: GetCareerPlan200RecommendationsItemEventDevelopsSkillsItem[];
  prerequisites: GetCareerPlan200RecommendationsItemEventPrerequisites;
  /** @items.pattern ^\d{4}-\d{2}-\d{2}$ */
  upcoming_sessions: string[];
};

export type GetCareerPlan200RecommendationsItemFactorsItemCategory = typeof GetCareerPlan200RecommendationsItemFactorsItemCategory[keyof typeof GetCareerPlan200RecommendationsItemFactorsItemCategory];


export const GetCareerPlan200RecommendationsItemFactorsItemCategory = {
  grade: 'grade',
  gap: 'gap',
  history: 'history',
  target: 'target',
} as const;

export type GetCareerPlan200RecommendationsItemFactorsItem = {
  id: string;
  category: GetCareerPlan200RecommendationsItemFactorsItemCategory;
  text: string;
};

export type GetCareerPlan200RecommendationsItemGainsItem = {
  skill_id: string;
  name: string;
  before: number;
  after: number;
  target: number;
};

export type GetCareerPlan200RecommendationsItem = {
  event: GetCareerPlan200RecommendationsItemEvent;
  score: number;
  factors: GetCareerPlan200RecommendationsItemFactorsItem[];
  /**
     * @nullable
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  next_session: string | null;
  gains: GetCareerPlan200RecommendationsItemGainsItem[];
  in_progress: boolean;
  explanation: string;
};

export type GetCareerPlan200MandatoryTasksItemStatus = typeof GetCareerPlan200MandatoryTasksItemStatus[keyof typeof GetCareerPlan200MandatoryTasksItemStatus];


export const GetCareerPlan200MandatoryTasksItemStatus = {
  in_progress: 'in_progress',
  dropped: 'dropped',
  no_show: 'no_show',
  declined: 'declined',
  overdue: 'overdue',
} as const;

export type GetCareerPlan200MandatoryTasksItem = {
  event_id: string;
  title: string;
  status: GetCareerPlan200MandatoryTasksItemStatus;
  /**
     * @nullable
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  due_date: string | null;
};

export type GetCareerPlan200 = {
  employee_id: string;
  current_position: GetCareerPlan200CurrentPosition;
  /** @nullable */
  career_goal: GetCareerPlan200CareerGoal;
  goal_source: GetCareerPlan200GoalSource;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  as_of_date: string;
  /**
     * @nullable
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  last_review_date: string | null;
  effective_skills: GetCareerPlan200EffectiveSkills;
  counted_completions: string[];
  assessment_note: string;
  /**
     * @minimum 0
     * @maximum 100
     * @nullable
     */
  readiness: number | null;
  /**
     * @minimum 0
     * @maximum 100
     * @nullable
     */
  projected_readiness: number | null;
  projected_skills: GetCareerPlan200ProjectedSkills;
  /** @maxItems 3 */
  trajectory: GetCareerPlan200TrajectoryItem[];
  gaps: GetCareerPlan200GapsItem[];
  /** @maxItems 3 */
  recommendations: GetCareerPlan200RecommendationsItem[];
  uncovered_skills: string[];
  mandatory_tasks: GetCareerPlan200MandatoryTasksItem[];
  warnings: string[];
};

export type GetCareerPlan400 = {
  message: string;
};

export type GetCareerPlan401 = {
  message: string;
};

export type GetCareerPlan403 = {
  message: string;
};

export type GetCareerPlan404 = {
  message: string;
};

export type GetCareerPlan409 = {
  message: string;
};

export type GetCareerPlan413 = {
  message: string;
};

export type GetCareerPlan429 = {
  message: string;
};

export type GetCareerPlan500 = {
  message: string;
};

export type GetCareerPlan503 = {
  message: string;
};

export type ChatWithCareerAdvisorBodyOneConversationHistoryItemRole = typeof ChatWithCareerAdvisorBodyOneConversationHistoryItemRole[keyof typeof ChatWithCareerAdvisorBodyOneConversationHistoryItemRole];


export const ChatWithCareerAdvisorBodyOneConversationHistoryItemRole = {
  user: 'user',
  assistant: 'assistant',
} as const;

export type ChatWithCareerAdvisorBodyOneConversationHistoryItem = {
  role: ChatWithCareerAdvisorBodyOneConversationHistoryItemRole;
  /**
     * @minLength 1
     * @maxLength 3000
     */
  content: string;
};

export type ChatWithCareerAdvisorBodyOne = {
  /**
     * @minLength 1
     * @maxLength 3000
     */
  message: string;
  /** @maxItems 20 */
  conversation_history?: ChatWithCareerAdvisorBodyOneConversationHistoryItem[];
};

export type ChatWithCareerAdvisorBodyTwoConversationHistoryItemRole = typeof ChatWithCareerAdvisorBodyTwoConversationHistoryItemRole[keyof typeof ChatWithCareerAdvisorBodyTwoConversationHistoryItemRole];


export const ChatWithCareerAdvisorBodyTwoConversationHistoryItemRole = {
  user: 'user',
  assistant: 'assistant',
} as const;

export type ChatWithCareerAdvisorBodyTwoConversationHistoryItem = {
  role: ChatWithCareerAdvisorBodyTwoConversationHistoryItemRole;
  /**
     * @minLength 1
     * @maxLength 3000
     */
  content: string;
};

export type ChatWithCareerAdvisorBodyTwo = {
  /**
     * @minLength 1
     * @maxLength 3000
     */
  message: string;
  /** @maxItems 20 */
  conversation_history?: ChatWithCareerAdvisorBodyTwoConversationHistoryItem[];
};

export type ChatWithCareerAdvisorBodyThreeConversationHistoryItemRole = typeof ChatWithCareerAdvisorBodyThreeConversationHistoryItemRole[keyof typeof ChatWithCareerAdvisorBodyThreeConversationHistoryItemRole];


export const ChatWithCareerAdvisorBodyThreeConversationHistoryItemRole = {
  user: 'user',
  assistant: 'assistant',
} as const;

export type ChatWithCareerAdvisorBodyThreeConversationHistoryItem = {
  role: ChatWithCareerAdvisorBodyThreeConversationHistoryItemRole;
  /**
     * @minLength 1
     * @maxLength 3000
     */
  content: string;
};

export type ChatWithCareerAdvisorBodyThree = {
  /**
     * @minLength 1
     * @maxLength 3000
     */
  message: string;
  /** @maxItems 20 */
  conversation_history?: ChatWithCareerAdvisorBodyThreeConversationHistoryItem[];
};

export type ChatWithCareerAdvisor200PlanCurrentPositionGrade = typeof ChatWithCareerAdvisor200PlanCurrentPositionGrade[keyof typeof ChatWithCareerAdvisor200PlanCurrentPositionGrade];


export const ChatWithCareerAdvisor200PlanCurrentPositionGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

export type ChatWithCareerAdvisor200PlanCurrentPosition = {
  role: string;
  grade: ChatWithCareerAdvisor200PlanCurrentPositionGrade;
};

export type ChatWithCareerAdvisor200PlanCareerGoalTargetGrade = typeof ChatWithCareerAdvisor200PlanCareerGoalTargetGrade[keyof typeof ChatWithCareerAdvisor200PlanCareerGoalTargetGrade];


export const ChatWithCareerAdvisor200PlanCareerGoalTargetGrade = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

/**
 * @nullable
 */
export type ChatWithCareerAdvisor200PlanCareerGoal = {
  /** @minLength 1 */
  target_role: string;
  target_grade: ChatWithCareerAdvisor200PlanCareerGoalTargetGrade;
} | null;

export type ChatWithCareerAdvisor200PlanGoalSource = typeof ChatWithCareerAdvisor200PlanGoalSource[keyof typeof ChatWithCareerAdvisor200PlanGoalSource];


export const ChatWithCareerAdvisor200PlanGoalSource = {
  explicit: 'explicit',
  next_grade: 'next_grade',
  none: 'none',
} as const;

export type ChatWithCareerAdvisor200PlanEffectiveSkills = { [key: string]: unknown };

export type ChatWithCareerAdvisor200PlanProjectedSkills = { [key: string]: unknown };

export type ChatWithCareerAdvisor200PlanTrajectoryItem = {
  event_id: string;
  /**
     * @minimum 0
     * @maximum 100
     * @nullable
     */
  readiness_before: number | null;
  /**
     * @minimum 0
     * @maximum 100
     * @nullable
     */
  readiness_after: number | null;
};

export type ChatWithCareerAdvisor200PlanGapsItem = {
  skill_id: string;
  name: string;
  /**
     * @minimum 0
     * @maximum 5
     */
  current: number;
  /**
     * @minimum 0
     * @maximum 5
     */
  required: number;
  /**
     * @minimum 1
     * @maximum 5
     */
  gap: number;
  critical: boolean;
  covered: boolean;
};

export type ChatWithCareerAdvisor200PlanRecommendationsItemEventFormat = typeof ChatWithCareerAdvisor200PlanRecommendationsItemEventFormat[keyof typeof ChatWithCareerAdvisor200PlanRecommendationsItemEventFormat];


export const ChatWithCareerAdvisor200PlanRecommendationsItemEventFormat = {
  online: 'online',
  offline: 'offline',
  self_paced: 'self_paced',
} as const;

export type ChatWithCareerAdvisor200PlanRecommendationsItemEventTargetGradesItem = typeof ChatWithCareerAdvisor200PlanRecommendationsItemEventTargetGradesItem[keyof typeof ChatWithCareerAdvisor200PlanRecommendationsItemEventTargetGradesItem];


export const ChatWithCareerAdvisor200PlanRecommendationsItemEventTargetGradesItem = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

export type ChatWithCareerAdvisor200PlanRecommendationsItemEventDevelopsSkillsItem = {
  skill_id: string;
  gain: number;
  /**
     * @minimum 0
     * @maximum 5
     */
  max_level: number;
};

export type ChatWithCareerAdvisor200PlanRecommendationsItemEventPrerequisites = { [key: string]: unknown };

export type ChatWithCareerAdvisor200PlanRecommendationsItemEvent = {
  event_id: string;
  title: string;
  description: string;
  type: string;
  format: ChatWithCareerAdvisor200PlanRecommendationsItemEventFormat;
  duration_hours: number;
  mandatory: boolean;
  target_roles: string[];
  target_grades: ChatWithCareerAdvisor200PlanRecommendationsItemEventTargetGradesItem[];
  develops_skills: ChatWithCareerAdvisor200PlanRecommendationsItemEventDevelopsSkillsItem[];
  prerequisites: ChatWithCareerAdvisor200PlanRecommendationsItemEventPrerequisites;
  /** @items.pattern ^\d{4}-\d{2}-\d{2}$ */
  upcoming_sessions: string[];
};

export type ChatWithCareerAdvisor200PlanRecommendationsItemFactorsItemCategory = typeof ChatWithCareerAdvisor200PlanRecommendationsItemFactorsItemCategory[keyof typeof ChatWithCareerAdvisor200PlanRecommendationsItemFactorsItemCategory];


export const ChatWithCareerAdvisor200PlanRecommendationsItemFactorsItemCategory = {
  grade: 'grade',
  gap: 'gap',
  history: 'history',
  target: 'target',
} as const;

export type ChatWithCareerAdvisor200PlanRecommendationsItemFactorsItem = {
  id: string;
  category: ChatWithCareerAdvisor200PlanRecommendationsItemFactorsItemCategory;
  text: string;
};

export type ChatWithCareerAdvisor200PlanRecommendationsItemGainsItem = {
  skill_id: string;
  name: string;
  before: number;
  after: number;
  target: number;
};

export type ChatWithCareerAdvisor200PlanRecommendationsItem = {
  event: ChatWithCareerAdvisor200PlanRecommendationsItemEvent;
  score: number;
  factors: ChatWithCareerAdvisor200PlanRecommendationsItemFactorsItem[];
  /**
     * @nullable
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  next_session: string | null;
  gains: ChatWithCareerAdvisor200PlanRecommendationsItemGainsItem[];
  in_progress: boolean;
  explanation: string;
};

export type ChatWithCareerAdvisor200PlanMandatoryTasksItemStatus = typeof ChatWithCareerAdvisor200PlanMandatoryTasksItemStatus[keyof typeof ChatWithCareerAdvisor200PlanMandatoryTasksItemStatus];


export const ChatWithCareerAdvisor200PlanMandatoryTasksItemStatus = {
  in_progress: 'in_progress',
  dropped: 'dropped',
  no_show: 'no_show',
  declined: 'declined',
  overdue: 'overdue',
} as const;

export type ChatWithCareerAdvisor200PlanMandatoryTasksItem = {
  event_id: string;
  title: string;
  status: ChatWithCareerAdvisor200PlanMandatoryTasksItemStatus;
  /**
     * @nullable
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  due_date: string | null;
};

export type ChatWithCareerAdvisor200Plan = {
  employee_id: string;
  current_position: ChatWithCareerAdvisor200PlanCurrentPosition;
  /** @nullable */
  career_goal: ChatWithCareerAdvisor200PlanCareerGoal;
  goal_source: ChatWithCareerAdvisor200PlanGoalSource;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  as_of_date: string;
  /**
     * @nullable
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  last_review_date: string | null;
  effective_skills: ChatWithCareerAdvisor200PlanEffectiveSkills;
  counted_completions: string[];
  assessment_note: string;
  /**
     * @minimum 0
     * @maximum 100
     * @nullable
     */
  readiness: number | null;
  /**
     * @minimum 0
     * @maximum 100
     * @nullable
     */
  projected_readiness: number | null;
  projected_skills: ChatWithCareerAdvisor200PlanProjectedSkills;
  /** @maxItems 3 */
  trajectory: ChatWithCareerAdvisor200PlanTrajectoryItem[];
  gaps: ChatWithCareerAdvisor200PlanGapsItem[];
  /** @maxItems 3 */
  recommendations: ChatWithCareerAdvisor200PlanRecommendationsItem[];
  uncovered_skills: string[];
  mandatory_tasks: ChatWithCareerAdvisor200PlanMandatoryTasksItem[];
  warnings: string[];
};

export type ChatWithCareerAdvisor200RecommendationsMode = typeof ChatWithCareerAdvisor200RecommendationsMode[keyof typeof ChatWithCareerAdvisor200RecommendationsMode];


export const ChatWithCareerAdvisor200RecommendationsMode = {
  ai: 'ai',
  rules: 'rules',
} as const;

export type ChatWithCareerAdvisor200RecommendationsRecommendationsItemEventFormat = typeof ChatWithCareerAdvisor200RecommendationsRecommendationsItemEventFormat[keyof typeof ChatWithCareerAdvisor200RecommendationsRecommendationsItemEventFormat];


export const ChatWithCareerAdvisor200RecommendationsRecommendationsItemEventFormat = {
  online: 'online',
  offline: 'offline',
  self_paced: 'self_paced',
} as const;

export type ChatWithCareerAdvisor200RecommendationsRecommendationsItemEventTargetGradesItem = typeof ChatWithCareerAdvisor200RecommendationsRecommendationsItemEventTargetGradesItem[keyof typeof ChatWithCareerAdvisor200RecommendationsRecommendationsItemEventTargetGradesItem];


export const ChatWithCareerAdvisor200RecommendationsRecommendationsItemEventTargetGradesItem = {
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior',
  Lead: 'Lead',
} as const;

export type ChatWithCareerAdvisor200RecommendationsRecommendationsItemEventDevelopsSkillsItem = {
  skill_id: string;
  gain: number;
  /**
     * @minimum 0
     * @maximum 5
     */
  max_level: number;
};

export type ChatWithCareerAdvisor200RecommendationsRecommendationsItemEventPrerequisites = { [key: string]: unknown };

export type ChatWithCareerAdvisor200RecommendationsRecommendationsItemEvent = {
  event_id: string;
  title: string;
  description: string;
  type: string;
  format: ChatWithCareerAdvisor200RecommendationsRecommendationsItemEventFormat;
  duration_hours: number;
  mandatory: boolean;
  target_roles: string[];
  target_grades: ChatWithCareerAdvisor200RecommendationsRecommendationsItemEventTargetGradesItem[];
  develops_skills: ChatWithCareerAdvisor200RecommendationsRecommendationsItemEventDevelopsSkillsItem[];
  prerequisites: ChatWithCareerAdvisor200RecommendationsRecommendationsItemEventPrerequisites;
  /** @items.pattern ^\d{4}-\d{2}-\d{2}$ */
  upcoming_sessions: string[];
};

export type ChatWithCareerAdvisor200RecommendationsRecommendationsItemFactorsItemCategory = typeof ChatWithCareerAdvisor200RecommendationsRecommendationsItemFactorsItemCategory[keyof typeof ChatWithCareerAdvisor200RecommendationsRecommendationsItemFactorsItemCategory];


export const ChatWithCareerAdvisor200RecommendationsRecommendationsItemFactorsItemCategory = {
  grade: 'grade',
  gap: 'gap',
  history: 'history',
  target: 'target',
} as const;

export type ChatWithCareerAdvisor200RecommendationsRecommendationsItemFactorsItem = {
  id: string;
  category: ChatWithCareerAdvisor200RecommendationsRecommendationsItemFactorsItemCategory;
  text: string;
};

export type ChatWithCareerAdvisor200RecommendationsRecommendationsItemGainsItem = {
  skill_id: string;
  name: string;
  before: number;
  after: number;
  target: number;
};

export type ChatWithCareerAdvisor200RecommendationsRecommendationsItem = {
  event: ChatWithCareerAdvisor200RecommendationsRecommendationsItemEvent;
  score: number;
  factors: ChatWithCareerAdvisor200RecommendationsRecommendationsItemFactorsItem[];
  /**
     * @nullable
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  next_session: string | null;
  gains: ChatWithCareerAdvisor200RecommendationsRecommendationsItemGainsItem[];
  in_progress: boolean;
  explanation: string;
};

export type ChatWithCareerAdvisor200Recommendations = {
  mode: ChatWithCareerAdvisor200RecommendationsMode;
  /** @nullable */
  model: string | null;
  message: string;
  /** @maxItems 3 */
  recommendations: ChatWithCareerAdvisor200RecommendationsRecommendationsItem[];
  generated_at: string;
  duration_ms: number;
};

export type ChatWithCareerAdvisor200 = {
  employee_id: string;
  reply: string;
  plan: ChatWithCareerAdvisor200Plan;
  recommendations: ChatWithCareerAdvisor200Recommendations;
};

export type ChatWithCareerAdvisor400 = {
  message: string;
};

export type ChatWithCareerAdvisor401 = {
  message: string;
};

export type ChatWithCareerAdvisor403 = {
  message: string;
};

export type ChatWithCareerAdvisor404 = {
  message: string;
};

export type ChatWithCareerAdvisor409 = {
  message: string;
};

export type ChatWithCareerAdvisor413 = {
  message: string;
};

export type ChatWithCareerAdvisor429 = {
  message: string;
};

export type ChatWithCareerAdvisor500 = {
  message: string;
};

export type ChatWithCareerAdvisor503 = {
  message: string;
};

export type GetHrOverview200EmployeesWithoutStepItem = {
  employee_id: string;
  full_name: string;
  role: string;
  reason: string;
};

export type GetHrOverview200SkillGapsItem = {
  skill_id: string;
  name: string;
  employees: number;
  average_gap: number;
};

export type GetHrOverview200ParticipationItem = {
  event_id: string;
  title: string;
  mandatory: boolean;
  completed: number;
  in_progress: number;
  other: number;
  total: number;
};

export type GetHrOverview200 = {
  total_employees: number;
  employees_without_step: GetHrOverview200EmployeesWithoutStepItem[];
  skill_gaps: GetHrOverview200SkillGapsItem[];
  participation: GetHrOverview200ParticipationItem[];
  as_of_date: string;
};

export type GetHrOverview400 = {
  message: string;
};

export type GetHrOverview401 = {
  message: string;
};

export type GetHrOverview403 = {
  message: string;
};

export type GetHrOverview404 = {
  message: string;
};

export type GetHrOverview409 = {
  message: string;
};

export type GetHrOverview413 = {
  message: string;
};

export type GetHrOverview429 = {
  message: string;
};

export type GetHrOverview500 = {
  message: string;
};

export type ImportDataBodyOne = {
  /** @maxLength 8388608 */
  employees_json: string;
  /** @maxLength 8388608 */
  history_csv: string;
};

export type ImportDataBodyTwo = {
  /** @maxLength 8388608 */
  employees_json: string;
  /** @maxLength 8388608 */
  history_csv: string;
};

export type ImportDataBodyThree = {
  /** @maxLength 8388608 */
  employees_json: string;
  /** @maxLength 8388608 */
  history_csv: string;
};

export type ImportData200 = {
  employees: number;
  history: number;
  message: string;
};

export type ImportData400 = {
  message: string;
};

export type ImportData401 = {
  message: string;
};

export type ImportData403 = {
  message: string;
};

export type ImportData404 = {
  message: string;
};

export type ImportData409 = {
  message: string;
};

export type ImportData413 = {
  message: string;
};

export type ImportData429 = {
  message: string;
};

export type ImportData500 = {
  message: string;
};

export const getCareerQuestAPI = () => {
/**
 * @summary Статус API и соединения с БД
 */
const health = (

 ) => {
      return customInstance<Health200>(
      {url: `/api/health`, method: 'GET'
    },
      );
    }

/**
 * Создает сессию на 12 часов. Cookie: HttpOnly, SameSite=Lax, Secure на HTTPS. Ограничение: 10 неудачных попыток на аккаунт за 15 минут.
 * @summary Войти по логину и паролю
 */
const login = (
    loginBody: LoginBodyOne | LoginBodyTwo | LoginBodyThree,
 ) => {
      return customInstance<Login200>(
      {url: `/api/auth/login`, method: 'POST',
      data: loginBody
    },
      );
    }

/**
 * @summary Текущий пользователь
 */
const getSession = (

 ) => {
      return customInstance<GetSession200>(
      {url: `/api/auth/session`, method: 'GET'
    },
      );
    }

/**
 * @summary Завершить текущую сессию
 */
const logout = (

 ) => {
      return customInstance<Logout200>(
      {url: `/api/auth/logout`, method: 'POST'
    },
      );
    }

/**
 * @summary Список сотрудников для HR
 */
const getEmployees = (

 ) => {
      return customInstance<GetEmployees200>(
      {url: `/api/employees`, method: 'GET'
    },
      );
    }

/**
 * Сотрудник получает только свой профиль; HR может просматривать любой. Readiness — покрытие требований цели, не вероятность повышения.
 * @summary Профиль и карьерная траектория
 */
const getProfile = (
    id: string,
 ) => {
      return customInstance<GetProfile200>(
      {url: `/api/employees/${id}`, method: 'GET'
    },
      );
    }

/**
 * Пара роли и грейда должна существовать в каталоге. null включает следующий грейд по умолчанию; у Lead следующего грейда нет.
 * @summary Изменить карьерную цель
 */
const updateGoal = (
    id: string,
    updateGoalBody: UpdateGoalBodyOne | UpdateGoalBodyTwo | UpdateGoalBodyThree,
 ) => {
      return customInstance<UpdateGoal200>(
      {url: `/api/employees/${id}/goal`, method: 'PATCH',
      data: updateGoalBody
    },
      );
    }

/**
 * Демонстрационное завершение на дату среза. Повторный запрос идемпотентен; обязательные мероприятия исключены. Это не подтверждение посещения реального обучения.
 * @summary Подтвердить выполнение и пересчитать навыки
 */
const completeActivity = (
    id: string,
    eventId: string,
    completeActivityBody: CompleteActivityBodyOne | CompleteActivityBodyTwo | CompleteActivityBodyThree,
 ) => {
      return customInstance<CompleteActivity200>(
      {url: `/api/employees/${id}/activities/${eventId}/complete`, method: 'POST',
      data: completeActivityBody
    },
      );
    }

/**
 * @summary Каталог навыков и профилей ролей
 */
const getCatalog = (

 ) => {
      return customInstance<GetCatalog200>(
      {url: `/api/catalog`, method: 'GET'
    },
      );
    }

/**
 * Агент выбирает только допустимые мероприятия и подтвержденные факторы из серверного контекста. При недоступности агента или модели возвращается mode=rules. Если допустимых шагов нет, массив пуст и приведена причина.
 * @summary Получить до трех объяснимых рекомендаций
 */
const getRecommendations = (
    id: string,
    getRecommendationsBody: GetRecommendationsBodyOne | GetRecommendationsBodyTwo | GetRecommendationsBodyThree,
 ) => {
      return customInstance<GetRecommendations200>(
      {url: `/api/employees/${id}/recommendations`, method: 'POST',
      data: getRecommendationsBody
    },
      );
    }

/**
 * Контекст профиля, каталога и истории формируется на сервере. План содержит расчетную траекторию, разрывы навыков и предупреждения; готовность не гарантирует повышение. При недоступности агента возвращается 503.
 * @summary Получить карьерный план и прогноз развития навыков
 */
const getCareerPlan = (
    id: string,
 ) => {
      return customInstance<GetCareerPlan200>(
      {url: `/api/employees/${id}/plan`, method: 'GET'
    },
      );
    }

/**
 * Клиент передает сообщение и до 20 реплик истории; контекст сотрудника формирует API после проверки доступа. Ответ включает план и рекомендации. При недоступности агента возвращается 503.
 * @summary Обсудить карьерное развитие с AI-советником
 */
const chatWithCareerAdvisor = (
    id: string,
    chatWithCareerAdvisorBody: ChatWithCareerAdvisorBodyOne | ChatWithCareerAdvisorBodyTwo | ChatWithCareerAdvisorBodyThree,
 ) => {
      return customInstance<ChatWithCareerAdvisor200>(
      {url: `/api/employees/${id}/chat`, method: 'POST',
      data: chatWithCareerAdvisorBody
    },
      );
    }

/**
 * @summary HR-сводка по дефицитам и участию
 */
const getHrOverview = (

 ) => {
      return customInstance<GetHrOverview200>(
      {url: `/api/hr/overview`, method: 'GET'
    },
      );
    }

/**
 * Только синтетические данные. Один файл может быть пустым. Проверяется весь объединенный набор, затем атомарно выполняется upsert по employee_id/record_id. Ошибка отменяет весь запрос. Импорт не выдает учетные записи и не меняет роли.
 * @summary Загрузить профили JSON и историю CSV
 */
const importData = (
    importDataBody: ImportDataBodyOne | ImportDataBodyTwo | ImportDataBodyThree,
 ) => {
      return customInstance<ImportData200>(
      {url: `/api/hr/import`, method: 'POST',
      data: importDataBody
    },
      );
    }

return {health,login,getSession,logout,getEmployees,getProfile,updateGoal,completeActivity,getCatalog,getRecommendations,getCareerPlan,chatWithCareerAdvisor,getHrOverview,importData}};
export type HealthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCareerQuestAPI>['health']>>>
export type LoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCareerQuestAPI>['login']>>>
export type GetSessionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCareerQuestAPI>['getSession']>>>
export type LogoutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCareerQuestAPI>['logout']>>>
export type GetEmployeesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCareerQuestAPI>['getEmployees']>>>
export type GetProfileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCareerQuestAPI>['getProfile']>>>
export type UpdateGoalResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCareerQuestAPI>['updateGoal']>>>
export type CompleteActivityResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCareerQuestAPI>['completeActivity']>>>
export type GetCatalogResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCareerQuestAPI>['getCatalog']>>>
export type GetRecommendationsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCareerQuestAPI>['getRecommendations']>>>
export type GetCareerPlanResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCareerQuestAPI>['getCareerPlan']>>>
export type ChatWithCareerAdvisorResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCareerQuestAPI>['chatWithCareerAdvisor']>>>
export type GetHrOverviewResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCareerQuestAPI>['getHrOverview']>>>
export type ImportDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCareerQuestAPI>['importData']>>>
